version: '4.26.0'

networks:
  backend:
  frontend:
  common_net:

services:
  web:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/web/staticfiles
    ports:
      - 8000:80
    env_file:
      - ./.env
    networks:
      - backend
      - frontend
    depends_on:
      - postgresdb
  postgresdb:
    image: "postgres:latest"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d netology_stocks_products" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@yandex.ru
#      - PGADMIN_DEFAULT_PASSWORD=adminpwd
#      - PGADMIN_DEFAULT_SERVER_MODE=False
#    networks:
#      - backend
#    ports:
#      - 5050:80
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - frontend
volumes:
  pgdata:
  static_volume: